sudo: false
language: php
php:
- 7.0
- 7.1
branches:
  only:
  - master
cache:
  directories:
  - "$HOME/.composer/cache/files"
install:
- mv /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ~/xdebug.ini
- composer update --prefer-dist
- mv ~/xdebug.ini /home/travis/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini
script:
- vendor/phpunit/phpunit/phpunit --coverage-clover build/logs/clover.xml
after_success:
- bash .travis_docgen.sh
env:
  global:
    secure: eFbmW33M0fZQkarSNoktApH1fSdEK5+ODj+MjR6Vo5bOtQwEoLv7XyK2+G2HSYPLRInKAev1m8U+vK7tGVfWJAcMhTp5vpRutU+Bg8EFJohpNYAsC/wQOoxAFu3SEp6GeM1U6R5iAAK2Hl612WhJHm3r+0+XvhunLU6IuTduienzqqW5Aj60Rf8gDvQaBRZG1x0cgBZeDVsdro9JM/rzhEpJk9ONkSc2wMzVYiXqzLO3IQMCXMwcmyfVI6t641yUsP3ctToNJddV4w6xs+7rMTfkCC6DKeY0fMQTCwIHpVc8tvJkhg/gkGqrdu35JiUIG+oFFa444PoukxywlvIBB9PBYVKNwgGsVjPI9UoM7ZPHLcT9hNYyqnl330QJO3V7pIH21wKPXkqnt6a2J3xcC7UTT8cCmu12jMJ8FJ50TtOeS9OiDaJAsGpv03QWvFtKXgoaJrUgWM3OlkfTQnzZ/Gv8+mWsODv6z6MYPsYbwNR3vjIDK0/umRFUsxuBGKi7nqmbkxqFpuhC3sp3NzMGiy1ZP5f1CVKIwxAkTsusC2568CcZEiH0xo0FN5JCNlmmQPhPFsO5YOmwMf84MnVRNt2j8V72q25/VBxCyJlFZxqNgRu37Msxg824Eld6M0RlEejgrscJ1A/C5KknCAnvC/+0tfVrpdX2pIe9HZ48cjM=
